apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-comments-ui-to-comments-dev
  namespace: chaos-mesh
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: comments-ui-dev
  direction: to
  target:
    mode: all
    selector:
      namespaces:
        - default
      labelSelectors:
        app: comments-dev
  delay:
    latency: "250ms"
    correlation: "100"
    jitter: "25ms"
  duration: "60s"
