kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-default-viewer-mqehc

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-default-viewer-mqehc
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: chaos-mesh
  name: role-chaos-runner-mqehc
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: ["podchaos", "networkchaos", "schedules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole-chaos-viewer-mqehc
rules:
- apiGroups: ["chaos-mesh.org"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-default-viewer-mqehc
  namespace: default
subjects:
- kind: ServiceAccount
  name: account-default-viewer-mqehc
  namespace: default
roleRef:
  kind: Role
  name: role-default-viewer-mqehc
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-chaos-runner-mqehc
  namespace: chaos-mesh
subjects:
- kind: ServiceAccount
  name: account-default-viewer-mqehc
  namespace: default
roleRef:
  kind: Role
  name: role-chaos-runner-mqehc
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-chaos-viewer-mqehc
subjects:
- kind: ServiceAccount
  name: account-default-viewer-mqehc
  namespace: default
roleRef:
  kind: ClusterRole
  name: clusterrole-chaos-viewer-mqehc
  apiGroup: rbac.authorization.k8s.io
