apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-pod-kill-random-hello-or-comments
  namespace: chaos-mesh
spec:
  schedule: "@every 10s"
  concurrencyPolicy: Forbid
  historyLimit: 1
  type: PodChaos
  podChaos:
    action: pod-kill
    mode: all
    selector:
      namespaces:
        - default
      expressionSelectors:
        - key: app
          operator: In
          values:
            - hello-dev
            - comments-dev
